### ISSUE TITLE
Confirm delete on job templates

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#102]

**Comment by Sispheor** [comment]
- show linked operations (and service name) before deletion if exist
- if the service does not have a create operation anymore (http://192.168.58.128:8000/settings/catalog/service/1/operations/add/). The "service add" form need to allow "create"
- if a service has no "create" operation --> cannot be requested

**Comment by Sispheor** [comment]
Done and merged in dev
