### ISSUE TITLE
Bug: resource attributes not initialized after adding a new one in the resource group

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#111]
**Describe the bug**
Resource attributes are not initialized after adding a new one in group

**To Reproduce**
1. Go to Resource groups page
2. Click on edit group
3. Click on add attribute
4. Choose name then add
5. Go back in Resource groups pagey
6. Click on resources in lower right corner of group card
7. New resource doesn't displayed because is never been initialized (NULL)

**Expected behavior**
Resources must be initialized when they are added

**Screenshots**
![image](https://user-images.githubusercontent.com/40194291/128828692-5308520f-0482-4712-babe-c529df592da9.png)

**GIT commit sha**
- b40301bc7a7300e346165243f98cbf05b796e4b9

**Comment by a-belhadj** [comment]
Done an merged in sub-dev
