### ISSUE TITLE
Cannot select "type = create" if I want to edit a newly added service

### ISSUE THREAD

**Issue by eschek87** [HewlettPackard/squest#115]
**Describe the bug**
I have added a new service and then want to edit the settings for this service like auto-accept and auto-process. I then can only select "update" and "delete" as type. The "create" type is missing. See screenshot

**Expected behavior**
"create" should be available in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/22763868/128889009-9ad490d5-03d3-4388-8c13-c2663c714c89.png)
![image](https://user-images.githubusercontent.com/22763868/128888673-80e669ee-638e-427d-816d-f4d88bb28a5d.png)

- Squest version or GIT commit number: latest master branch
- Ansible Tower/AWX version: 17.0.1

**Comment by a-belhadj** [comment]
I work on that now

**Comment by eschek87** [comment]
But if I want to change the "Process Timeout" I need to go to these settings. And after hitting "Edit Operation" button the type is then "update" because I cannot select "create" in the dropdown.

**Comment by a-belhadj** [comment]
Done and merge in sub-dev

You can now edit the create operation
