### ISSUE TITLE
Mail notification not working if SQUEST_HOST is defined with a port number

### ISSUE THREAD

**Issue by eschek87** [HewlettPackard/squest#117]
Hi,

if I specifiy SQUEST_HOST = "fqdn:8443" in development.py the system uses squest@fqdn:8443 as the sender

Regards,
Stephan

**Comment by Sispheor** [comment]
Hi.
Here it's a Django settings.
You need to use EMAIL_PORT.
On our side we need to add it to the documentation.

**Comment by eschek87** [comment]
Hi,
I know the email_port setting. That's not the problem what I mean. It seems that the system uses the information from variable SQUEST_HOST as the mail address for the sender. So I published the squest frontend via gunicorn with port 8443 because I already have another website available at port 443. So I thought I can specify SQUEST_HOST = "fqdn:8443" so that the generated link in the submitted, accepted mails etc. is correct.

**Comment by Sispheor** [comment]
Done and merged in dev.
SQUEST_EMAIL_HOST variable added to the conf.
