### ISSUE TITLE
Announcement TZ issue between 0 and 2 am

### ISSUE THREAD

**Issue by a-belhadj** [HewlettPackard/squest#123]
**Describe the bug**
The test tests/test_views/admin/announcement/test_announcement_urls.py:44 fails at 1:45am (Europe/Paris) 
with an error : Date start: The start date must not be in the past

Here is the result of timezone.now() at 1:49 am (Europe/Paris)
```
2021-08-11 23:49:11.231904+00:00
```

**Expected behavior**
No crash

- Squest version or GIT commit number:  e7ec01ff050b4e650cbcb296bbe79681a83b0748

**Comment by EliasBoulharts** [comment]
Closed and merged in sub-dev
