### ISSUE TITLE
Request does not changed from "PROCESSING" to "COMPLETE"

### ISSUE THREAD

**Issue by eschek87** [HewlettPackard/squest#126]
**Describe the bug**
Request does not changed from "PROCESSING" to "COMPLETE". In AWX/Tower the job has the status "Successful".
Is there a way to see why the status in squest is not changed to "COMPLETE"?

**Expected behavior**
Request has status "COMPLETE" in squest when the status in awx/tower is "Successful".

- Squest version or GIT commit number: latest from master branch
- Ansible Tower/AWX version: 17.0.0.1

**Comment by Sispheor** [comment]
Can you docker logs both celery container?

**Comment by eschek87** [comment]
Ok, celery was not started. Thanks!

**Comment by Sispheor** [comment]
You scared me 😂
I was already digging into the code.
Perfect then.
Thanks for beta testing all of this
