### ISSUE TITLE
Switch ordering of "Admin" and "User" survey fields in accept request admin view

### ISSUE THREAD

**Issue by eschek87** [HewlettPackard/squest#128]
Maybe it's better to have at first the "user" survey fields and then below the "admin" survey fields in the accpet request view. So that the admin can check at first the user inputs (if things are unclear ask more info from user), before going to set the admin inputs....what do you think?

Regards,
Stephan

**Comment by a-belhadj** [comment]
Good suggestion, see you in the next release !

**Comment by Sispheor** [comment]
I confirm that it's a good point.
Go for it.

**Comment by Sispheor** [comment]
Done and merged in dev
