### ISSUE TITLE
All diagrams are not properly rendered on github.io

### ISSUE THREAD

**Issue by ericzolf** [HewlettPackard/squest#133]
As the subject says, an example https://hewlettpackard.github.io/squest/lifecycle_management/:

![image](https://user-images.githubusercontent.com/3105685/130589790-b9372e64-3d2f-49c8-8469-07567cbf6109.png)

**Comment by Sispheor** [comment]
Hi.
Weird,
It's ok on my smartphone using chrome Android.
What is your browser?

**Comment by ericzolf** [comment]
Ups, sorry, JavaScript was disabled. I wasn't aware that the graphics depend on it, I'm used to asciidoc and plantuml where the diagrams are pre-rendered. Sorry for the noise!
