### ISSUE TITLE
LDAP not working

### ISSUE THREAD

**Issue by eschek87** [HewlettPackard/squest#18]
I tried different settings in ldap_config.py and also read the django docs and double check the config.
But every time I receive "AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance". Can you check this? Manually running a ldapsearch on command line works fine.

Regards,
Stephan

**Comment by Sispheor** [comment]
This is the [LDAP module doc](https://django-auth-ldap.readthedocs.io/en/latest/authentication.html).

There is nothing more I can do on my side as it depends on your own conf here. There is no added code to manage ldap connections in Squest.

**Comment by eschek87** [comment]
Ok, thanks. Wired. If I put the ldap config in /Squest/settings/development.py it works

**Comment by Sispheor** [comment]
The flag [is here](https://github.com/HewlettPackard/squest/blob/master/Squest/settings/development.py#L120) in the file.
So if you placed the Boolean at the end of the file the LDAP config hasn't been loaded.
