### ISSUE TITLE
Inconsistent mail notifications?

### ISSUE THREAD

**Issue by eschek87** [HewlettPackard/squest#20]
I have configured a service for the service catalog and the mail notifications "from" address is different:
SUBMITTED: from user that requested the service
ACCEPTED: from "admin mail address"
PROCESSING: from "admin mail address"
COMPLETED: from "squest@SQUEST_HOST"

Works as expected? I would expect that "from" should be always squest@SQUEST_HOST

**Comment by Sispheor** [comment]
Yes it's the expected behavior.
We wanted to know who has performed actions.
But maybe the email should be always squest indeed

**Comment by Sispheor** [comment]
Fixed and merged in dev branch.

Note that we will investigate if we could relay on the [Tower notification system](https://docs.ansible.com/ansible-tower/latest/html/userguide/notifications.html). Via the hook feature we plan to implement.
