### ISSUE TITLE
Feature: create instance from the API

### ISSUE THREAD

**Issue by magnusolsson80** [HewlettPackard/squest#200]
**Description of the feature**
Our ansible playbook can install multiple servers in parallel. I would like to see that possibility to install multiple instances with the same configuration in one go. 

Multiple server installs are not possible today if I understand it correctly.

**Comment by Sispheor** [comment]
Hi,
Not sure to understand exactly your need.
You want to install multiple server of what?

You want to create multiple instance from a single service?

**Comment by magnusolsson80** [comment]
Correct. I want the abillity to create multiple instances with the same configuration under a service catalog item. 

Correct me if I get this totaly wrong but today you can only process one instance at a time.

Sorry for beeing unclear.. :-(

**Comment by Sispheor** [comment]
Yes so far one request gives one instance.
But, in futur release we will add the ability to create instance from the API.
So, you will be able to create instance from the executed playbook.

**Comment by magnusolsson80** [comment]
Ok.. I understand. It is a little bit of "ping pong" in between the ansible/awx tower and squest servers, but it will work.

**Comment by Sispheor** [comment]
We can the ability to have a new flag in "instance" which could be "parent".
So you can create "child" linked to the main service.

Like. The user asked for a service K8S, a service named K8S is created, and from the API you create child VMs that have been created behind the scene to support this service.

I know that force to place some task in the playbook side but it allows us to be very generic.

**Comment by Sispheor** [comment]
Done and merged in dev.
Will be a part of the v1 release.
