### ISSUE TITLE
Authentication credentials not provided

### ISSUE THREAD

**Issue by magnusolsson80** [HewlettPackard/squest#207]
**Describe the bug**
URI authentication does not work with API. 

**Ansible code**
    - name: Update spec of the instance via the squest API
      uri:
        url: "{{ squest_api_url }}service_catalog/admin/instance/{{ squest['request']['instance']['id'] }}/" # do not forget the last slash
        user: "admin"
        password: "admin"
        method: PATCH
        body:
          spec:
            foo: "bar"
        force_basic_auth: yes
        status_code: 200
        body_format: json
 
**Ansible output**
$ ansible-playbook squest_callback_test.yml  PLAY [Test Callback to Squest] *************************************************************************************************************************************************************************************************************** TASK [debug] *********************************************************************************************************************************************************************************************************************************

Wednesday 29 September 2021  14:38:11 +0200 (0:00:00.021)       0:00:00.021 *** 

ok: [localhost] => {​​​​​​

    "msg": "http://example.domain.com/api/service_catalog/admin/instance/5/"

}​​​​​​ TASK [Update spec of the instance via the squest API] ****************************************************************************************************************************************************************************************

Wednesday 29 September 2021  14:38:11 +0200 (0:00:00.044)       0:00:00.066 *** 

fatal: [localhost]: FAILED! => {​​​​​​"allow": "GET, PUT, PATCH, HEAD, OPTIONS", "changed": false, "connection": "close", "content": "{​​​​​​\"detail\":\"Authentication credentials were not provided.\"}​​​​​​", "content_length": "58", "content_type": "application/json", "date": "Wed, 29 Sep 2021 12:38:11 GMT", "elapsed": 0, "json": {​​​​​​"detail": "Authentication credentials were not provided."}​​​​​​, "msg": "Status code was 403 and not [200]: HTTP Error 403: Forbidden", "redirected": false, "referrer_policy": "same-origin", "server": "nginx", "status": 403, "url": "http://example.domain.com/api/service_catalog/********/instance/5/", "vary": "Accept, Cookie", "x_content_type_options": "nosniff", "x_frame_options": "DENY"}​​​​​​

[2:38 PM] Robin Jonsson
[rojon8@fedora ansible_test]$ ansible-playbook squest_callback_test.yml  PLAY [Test Callback to Squest] *************************************************************************************************************************************************************************************************************** TASK [debug] *********************************************************************************************************************************************************************************************************************************

Wednesday 29 September 2021  14:38:11 +0200 (0:00:00.021)       0:00:00.021 *** 

ok: [localhost] => {​​​​​​

    "msg": "http://example.domain.com/api/service_catalog/admin/instance/5/"

}​​​​​​ TASK [Update spec of the instance via the squest API] ****************************************************************************************************************************************************************************************

Wednesday 29 September 2021  14:38:11 +0200 (0:00:00.044)       0:00:00.066 *** 

fatal: [localhost]: FAILED! => {​​​​​​"allow": "GET, PUT, PATCH, HEAD, OPTIONS", "changed": false, "connection": "close", "content": "{​​​​​​\"detail\":\"Authentication credentials were not provided.\"}​​​​​​", "content_length": "58", "content_type": "application/json", "date": "Wed, 29 Sep 2021 12:38:11 GMT", "elapsed": 0, "json": {​​​​​​"detail": "Authentication credentials were not provided."}​​​​​​, "msg": "Status code was 403 and not [200]: HTTP Error 403: Forbidden", "redirected": false, "referrer_policy": "same-origin", "server": "nginx", "status": 403, "url": "http://example.domain.com/api/service_catalog/********/instance/5/", "vary": "Accept, Cookie", "x_content_type_options": "nosniff", "x_frame_options": "DENY"}​​​​​​

**Versions**
- Squest version or GIT commit number:  9d9d7c18f558ed60e9e2e87241192cc067635a89
- Ansible Tower/AWX version: 3.8.3

**Comment by Sispheor** [comment]
As you are using the dev branch. You need to create a token instead.

**Comment by Sispheor** [comment]
[Example here](https://github.com/HewlettPackard/squest/blob/dev/playbook_examples/provision_resource.yml#L38)

**Comment by Sispheor** [comment]
I hope it's ok for you. I close this one.
Fell free to open it back if needed.
