### ISSUE TITLE
Usage of day 2 operations?

### ISSUE THREAD

**Issue by eschek87** [HewlettPackard/squest#22]
How can I use day 2 operations? Do I need special extra_vars in ansible tower or in the playbook (for create/update/delete)?

**Comment by Sispheor** [comment]
Via the creation playbook, at the end of the process, you send to the squest API a json payload that contains all info that will allow you later to retrieve the created instance.
This json payload is then automatically added as extra_vars when using opeation of kind "delete" or "update".
I haven't had the time to document nicely this part. But the API doc is available once squest as started via the URL `/swagger`.

**Comment by eschek87** [comment]
Do you have an example or some screenshots? I don't know what you mean...
I tried accessing URL /swagger without success.

**Comment by Sispheor** [comment]
Forgot to precise that the doc is not yet merged in master. You need to checkout the dev branch if you want to give a try.
I'll add a full example with playbook example code as soon as possible.

**Comment by Sispheor** [comment]
Swagger API doc has been merged in master.

The idea is to update the target "instance" with the json "spec" you want. Like an ID or something that will help an update playbook to retrieve the resource.  You can use the URI Ansible module for this.
I'll add a playbook example in the doc.
![image](https://user-images.githubusercontent.com/2573405/123054235-f593e480-d404-11eb-8d59-bfdacb72b5a1.png)

**Comment by Sispheor** [comment]
Doc updated with[ day 2 operations ](https://hewlettpackard.github.io/squest/lifecycle_management/).
Hope it helps, @eschek87
