### ISSUE TITLE
Feature: Billing group quota

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#228]
Create generic quota attribute the ones we declare in resource group.

Example of usage:

- I set a quota attribute name "vCPU" to my billing group
- Each instantiated "Resource" can be linked to the quota attribute
- I retreieve as an admin a simplified view of consumed quota for each billing group

Second usage: auto approval
- When somebody request a service, hook can be executed with a playbook that check the the quota and call the squest API to auto approve or not the request depending on the quota

**Comment by mr-falken** [comment]
This would be such a great feature for enabling auto approval process..looking forward to it :)

**Comment by Sispheor** [comment]
Proposed database update:
![image](https://user-images.githubusercontent.com/2573405/146945321-4d305c51-8f84-41e5-b3cb-aad4708304f8.png)

**Comment by Sispheor** [comment]
Done and merged in dev.
Doc and API endpoint to be added later. Both are tracked in different issues. 
I close this one.
