### ISSUE TITLE
Bug: Display resource pool list (percentage color)

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#255]
**Describe the bug**
When a pool has a consumer but no producer, we have an error in the list of resource pools.

**To Reproduce**
1. Create resource pool
2. Create resource group consume from the pool
3. Open resource pool list

**Expected behavior**
Colored the bar in gray when the percentage is N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/40194291/139445356-ba21a55f-244b-4f65-9c04-9e559e8b018c.png)

**Additional context**

- Squest version or GIT commit number: v1.2b - 9d3ff6
- Ansible Tower/AWX version:

**Comment by Sispheor** [comment]
Done and merged in dev branch
