### ISSUE TITLE
"Instance by billing" graph not visible when there are many billing groups

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#271]
**Describe the bug**
When there are many billing groups, the graph is not visible in the Dashboard page.

**Screenshots**
![image](https://user-images.githubusercontent.com/40194291/142837594-599de22b-7b78-4307-b850-e620e8d3ac5b.png)

- Squest version or GIT commit number: v1.3b - 49be0b

**Comment by Sispheor** [comment]
Feature removed in the last dev branch.
Metrics will be managed by prometheus/grafana.
I close this one.
