### ISSUE TITLE
Bug: ResourceGroupAttributeDefinition matching query does not existon resource page

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#300]
resource_tracker/resource_group/1/resources/

**Comment by EliasBoulharts** [comment]
Missing CASCADE on deletion of ResourceGroupAttributeDefinition

**Comment by EliasBoulharts** [comment]
ResourceTable need to be updated for each instance (use a standard view)

**Comment by Sispheor** [comment]
Done and merged in dev branch
