### ISSUE TITLE
Auto resource expiration

### ISSUE THREAD

**Issue by mr-falken** [HewlettPackard/squest#358]
From time to time we need to provide "time bounded" resources, like vm for students that we need to delete after a certain period of time.

It'd be nice to have a mapping between groups/resource types where admin could specify whenever expiration date is mandatory during request.

Deletion of resources would obviously happen as is done at the moment, invoking a specific playbook, but with a scheduled job server side without human intervention.

**Comment by Sispheor** [comment]
Hi,

I think you can already achieved this by adding a field to your survey to capture the max amount of time the resource will stay alive.
From this field, your tower playbook called by squest could  can create a scheduled job ([from Tower API ](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Projects/Projects_projects_schedules_create) or Ansible Tower module) that will schedule the deletion of the created resource and call squest to switch the instance state to "deleted".

**Comment by mr-falken** [comment]
Hi,
that would technically work, but I'd like to keep my playbook away from knowing about squest/tower: it's my "separation of concerns" paranoia in designing architecutres ;)

**Comment by Sispheor** [comment]
The current design of Squest is to use the API to push "spec" about the created instance.
 It means that even if the feature you are describing was implemented it could not work without making your playbook aware of Squest to push metadata that are required to find back the instance to delete.

**Comment by mr-falken** [comment]
So what I could probably do is to write a "wrapper" playbook, to keep my original playbook clean without filling it with "if" to make it work outside squest/tower usage.

I'll spend some time over it, thanks for the idea :)
