### ISSUE TITLE
Getting details of user requesting the service in ansible vars

### ISSUE THREAD

**Issue by mr-falken** [HewlettPackard/squest#368]
It'd be nice to have details (i.e. username, email, etc) of the user submitting the request filled into ansible vars.

I'm using squest -> awx to provision vm in vcenter environment and I'd like to set vm attributes to specify contact person and other details: I can set those attributes via ansible, but in this case I'm missing user's value.

In the squest part of the payload I can just see squest user id (squest.user field) while variables as "awx_user_name" or "awx_user_email" are filled with details of the awx user been impersonated by awx application.

**Comment by Sispheor** [comment]
You can perform a GET to the profile api (​/profiles​/user​/{id}​/) to get info on the user.
If it's what you are looking for.

**Comment by mr-falken** [comment]
Yep, that's the idea: since user id is already sent in the squest vars payload I thought it'd been cleaner to receive other details as well - like awx does in the awx_* vars.

An authenticated GET request to squest might surely do the trick, if that's not easy to implement.

**Comment by Sispheor** [comment]
On our side we've decided to send minimal json serializer with only IDs. So the admin is then free to perform any API call to get details behind those IDs.

**Comment by mr-falken** [comment]
Ok, thanks for explaining: I'll go for the REST API based solution :)
