### ISSUE TITLE
Feature: Support of Openid connect authentication protocol

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#386]

**Comment by miketoupin** [comment]
Really worthy pursuing. I might be putting some time to test this on my fork. I will let you know if I can make this works with Azure AAD.

**Comment by miketoupin** [comment]
Really worthy pursuing. I might be putting some time to test this on my fork. I will let you know if I can make this works with Azure AAD.

**Comment by EliasBoulharts** [comment]
Close by @MWY3510 in PR #708.
