### ISSUE TITLE
Feature: day 2 operations: survey pre filled from spec

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#387]
As an example, I order a new service "Virtal Machine". The AWX survey ask therefore options like name, CPU and memory. Later I'll update the existing instance using the update operation, the CPU and memory field are prefilled with the current value from specs.

**Comment by EliasBoulharts** [comment]
prefilled with the previous completed request (full_survey field) may be better

**Comment by rooso** [comment]
I really like the idea of the "ansible friendly" version. Was just thinking about dropdown lists, will these also possible for fields of this type?

**Comment by Sispheor** [comment]
Done and merged in dev branch
