### ISSUE TITLE
Enhancement: add a button to disable/enable a service from the catalog

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#39]
After changing Tower/AWX survey, we must synchronize job templates on squest.
Do we update survey when is updated on Tower automatically or do we ask to update it manually?

**Comment by Sispheor** [comment]
- [ ] add a note in the doc to precise that the behavior is to update manually from squest once the survey has been changed on Tower
- [ ] add a button to disable/enable a service

**Comment by EliasBoulharts** [comment]
Redirect to edit the create survey (settings/catalog/service/<service_id>/operations/<operation_id>/survey/) after service creation (replace add service button by continue button)

**Comment by Sispheor** [comment]
Done and merged in dev
