### ISSUE TITLE
Duplicated Job Templates on sQuest when starting celery after two sync

### ISSUE THREAD

**Issue by a-belhadj** [HewlettPackard/squest#40]
![image](https://user-images.githubusercontent.com/82872898/124947898-862b1100-e010-11eb-8b9b-178dfd7f8fb5.png)

Steps to reproduce:

0. Launch development server without celery worker
1. Add a tower
2. Sync job templates
3. Sync job templates again
4. Start the celery worker: `celery -A service_catalog worker -l info`

DB Screenshot:
![image](https://user-images.githubusercontent.com/82872898/124948354-e457f400-e010-11eb-9df6-c7d2c80ea5d0.png)

Currently on commit : 46302ff (upstream/resoure_tracker)

**Comment by Sispheor** [comment]
Fixed and merged in dev
