### ISSUE TITLE
[Enhancement] Caution against data races in calculation

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#404]
add [select_for_update](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#select-for-update) in calculation:
  - QuotaBinding--> refresh_consumed
  - ResourceAttribute --> quota_bindings_update_consumed
  - ResourcePoolAttributeDefinition --> calculate_total_produced and calculate_total_consumed

**Comment by Sispheor** [comment]
After one year in prod we can close this one.
