### ISSUE TITLE
Cannot create survey with variable name "instance_name"

### ISSUE THREAD

**Issue by cclement-perrin-acoss** [HewlettPackard/squest#423]
**Describe the bug**

**To Reproduce**
1. Go to 'Tower/AWX and create a template with a survey field named "instance_name"
2. Go on SQUEST and create a service linked to your previous template
3. See error, the survey field isntance_name is not available on SQUEST side

**Expected behavior**
instance_name field displayed on SQUEST or warning in documentation saying you cannot use "instance_name" as a variable in your AWX/Tower survey.

**Comment by Sispheor** [comment]
😅 indeed.
We should have prefixed this variable name.
As a workaround you already guessed that you need to use another name.
We'll keep this opened so we can plan to fix it. As it's placed in multiple place in our code we'll need to take our time to test it correctly.

Sorry for the weird behavior.

**Comment by Sispheor** [comment]
Done and merged in dev branch
