### ISSUE TITLE
Enhancement: view in UI who applied the new state of a request

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#439]

**Comment by wilf1rst** [comment]
Hello @Sispheor,

we worked in 2020/2021 to create an ITSM tool dedicated to new server requests.

To join the conversation here is how we envisioned the history display at the request level:
<img src="https://user-images.githubusercontent.com/6798484/183898272-90635d3e-5739-4366-9dcf-1e5521c0c931.png" width=60% height=60%>

And displaying the global context of a request:
![request-page-sr-blurred](https://user-images.githubusercontent.com/6798484/183898329-e9e44a25-4833-4b0b-a48e-855f880767ca.png)

Thoses screenshot don't reflect the last versions we had in prod but as we choose to discontinue our product I don't have a more recent screenshots. We never had the time and resources to get to GA and now we will re-use the Ansible playbook / Terraform templates with Squest ;)

**Comment by Sispheor** [comment]
Hi, thanks for sharing.
This feature is something we have in mind. Actually linked to a global "changelog" on all our objects.
Thanks for the screenshots it will help to mockup something.

Hope Squest is good enough as a replacement then :).

**Comment by Sispheor** [comment]
Done and merged in dev branch.
