### ISSUE TITLE
Feature: Validate the content of a service fields in a service catalog with rules

### ISSUE THREAD

**Issue by kogarastu** [HewlettPackard/squest#453]
When a user fill a free text field in a service for a tower/awx job template , there's nothing that verify the content before the request is validated. 
Il would be interesting to control the content of these fields by implementing regex for each fields with type free text.
This feature would permit to avoid that the job failed because the content of a field is not with a good format ( ip address, fqdn...)

thanks by advance.

**Comment by EliasBoulharts** [comment]
Hello,

First of all thank you for your feedback. This already did with the PR #442 (validation can be custom with python validator so regex is supported).

It will available in the next release.

**Comment by kogarastu** [comment]
Hi, That's a good news !!!  Thanks a lot for this product !!
