### ISSUE TITLE
Link quotas to cost value (money)

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#502]
It might be useful to have a single unit of measurement to count the cost of resources. Money is the most generic unit to reflect all types of resources. Currencies could be chosen by an environment variable.
Also the fields in the survey could be linked to resource to estimate the cost of the requested service (displayed to the end-user).

E.g. : 
vCPU = 1$
CPU = 8$
memory = 0.5$

**Comment by Sispheor** [comment]
The quota is going to be refactored. But we won't link it to real cost value. each Squest admin is free to do it with an external tool.
