### ISSUE TITLE
Feature : deployment on kubernetes

### ISSUE THREAD

**Issue by vdveldet** [HewlettPackard/squest#508]
**Deploy to Kubernetes**
I would like a deployment on to Kubernetes in order to make the squest portal more highly availale.
It looks like there is only a docker-compose deployment available. 

An operator that will depploy and configure all components of squest.

**Comment by Sispheor** [comment]
Hi,

This is definitely in our pipe. It's a must have nowaday and we know that.
It's just a matter of time. We are working a lot on our instance of squest in prod here in HPE. 

We'll provide this officially asap, but, you can already use [this project](https://github.com/slarimore02/squest-k8s-deployment) made by a member of the community (@slarimore02).

**Comment by LennertMertens** [comment]
How is this going? Also interested in an OpenShift compatible installation.

**Comment by beerfranz** [comment]
Hello! I can provide an helm chart to install Squest and its dependencies.
What is the best way ?
1. HewlettPackard create a git repo to hosts this helm chart, then I can fork the repo and send my updates
2. I fork this repo and send my updates in a /charts directory
3. Other idea ?

A CI/CD config will be needed to automatically build and publish the chart.

**Comment by Sispheor** [comment]
This feature is ongoing. You can take a look to my fork there is a dedicated branch that can be tested. It's based on ansible.

**Comment by beerfranz** [comment]
ok, nice! I will publish an helm chart too. It's more K8s specific than ansible.

**Comment by Sispheor** [comment]
Yes Helm is more specific to K8S. But it's a fire and forget tool that doesn't really handle what a production deployment can need.
And as the helm chart will need some dependencies to operators you would have to wrap anyway the install with some code to be able to deploy the full app from scratch. 
But yes it can be cool to have both and see what are the limitations or advantages of each solution.

**Comment by beerfranz** [comment]
Agreed, the helm chart won't be enough for production. But peoples can deploy the helm chart using their tools/stack, like an ansible playbook (using kubernetes.core.helm module), or a gitops tool like argocd or fluxd (still configured with a lovely ansible playbook ^^ )

**Comment by Sispheor** [comment]
K8S deployment now available as beta feature.
Fell free to give us a feedback on this !
