### ISSUE TITLE
Migration guidelines

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#509]
1. Service catalog
    1. Define service: Day 1 and day 2 (think about variables you need to perform all your operations)
    2. Code playbooks
       1. List inputs
       2. Magic
       3. Generates specs and create a resource
    3. Split survey fields
       1. User fields
       2. Admin fields
    4. Split instance specs
       1. User specs
       2. Admin specs
    5. Migration of your old datas
       1. Current Source of Truth to Squest via API:
           1. Define graphs with Resource Groups, Resource Pools and Resources (optional)
           2. Create Resource Pools (optional)
           4. Create Resource Groups (at least one used to place resoufc
           5. Create Instance
           6. Create Resources

**Comment by Sispheor** [comment]
Close as finally not needed. And squest evolved since.
