### ISSUE TITLE
Error while accepting request via API

### ISSUE THREAD

**Issue by mr-falken** [HewlettPackard/squest#524]
Like discussed here https://gitter.im/HewlettPackard/squest?at=63038a0c9994996293ffe438 I am trying to implement a custom approval business logic in a python filter triggered by a global hook on request submission.

After some debug on the python module itself, I tried to use the "accept/reject" api via CURL to reduce the debug complexity, but it still throws an error.

That's the curl command : 

`curl -vvv -X POST "https://[...]/api/service_catalog/request/233/accept/" -H  "accept: application/json" -H  "authorization: Bearer [...]"`

And the error is : 

`{"required":"This field is required.","null":"This field may not be null.","invalid":"Invalid data. Expected a dictionary, but got {datatype}."}`

Please note that : 
 - Request is in the "Submitted" state
 - Same error is thrown when calling the "reject" api (https://[...]/api/service_catalog/request/233/reject/)
 - The "cancel" api is working as expected

Seems like I am missing some parameters, but looking at the swagger those apis don't need any payload, just request id in query string.

**Comment by Sispheor** [comment]
Hi,

Do you have a survey attached?

Do you have an example config we could apply on our side to reproduce the error?

Thanks.

**Comment by EliasBoulharts** [comment]
Hello,

To accept the request you must give the full survey filled.

E.g:
``` json
{
  "test": "test"
}
```

I will update the swagger description to be clear.

Sorry for the delay.

**Comment by mr-falken** [comment]
Hi @EliasBoulharts ,
 thanks for the hint, on Friday I tried to pass a { fill_in_survey: { [...] } } json but without any luck: with your suggestion I just passed the values without "fill_in_survey" header and it worked :)
 
 It doesn't seem to auto process the request (even though auto process is enabled for that operation): is that expected ?
Should I call the "process" api and ignore the "auto process" flag when using apis ?

Thanks! :)

**Comment by Sispheor** [comment]
We've identified a bug. The request cannot be accepted when a survey is not defined.

**Comment by Sispheor** [comment]
To summarize:

- [ ] POST Accept on swagger not well documented
- [ ] Bug when no survey attached to a service when accepting via api
- [ ] Auto process not working after accepting a request via api

**Comment by mr-falken** [comment]
Sorry to have triggered all those bugs ;)

I'm pasting here another issue related to the accept api I found out while trying to solve the missed auto process.
My survey is a simple json like this (please note number without double quotes): 

```
{
  "delete": 2
}

```
The survey is filled correctly when requesting the resource via squest UI.
When I POST (via curl or python) the accept method indicating the survey as Elias suggested, the number gets converted as a string

```
{
  "delete": "2"
}
```

This brings the process operation to fail with a `'NoneType' object has no attribute 'id'` - not triggered if I correct the json survey by hand and remove double quotes.

The curl to post the accept method is like this : 

`curl -X POST "https://[...]/api/service_catalog/request/233/accept/" -d '{ "delete_in_days": 2 }' -H 'Content-Type: application/json' -H  "accept: application/json" -H  "authorization: Bearer [...]"`

Same result when posting via python:

```
headers = { "Authorization": "Bearer [...]", 
            "Accept": "application/json",
            "Content-Type": "application/json" }

d = { 'delete_in_days': 2 }

endpoint = "https://[...]/api/service_catalog/request/233/accept/"
response = requests.post(endpoint, data=json.dumps(d), headers=headers)

```

**Comment by EliasBoulharts** [comment]
Close with #526

**Comment by Sispheor** [comment]
The dev image is built automatically. You can use the "dev" tag when pulling it.
