### ISSUE TITLE
Accepting request via api with integer value in survey

### ISSUE THREAD

**Issue by mr-falken** [HewlettPackard/squest#537]
Hi,
  this is related to [this](https://github.com/HewlettPackard/squest/issues/524#issuecomment-1237214201) comment to another issue: I'm pasting everything again here for convenience.

SQuest is running at latest stable version (v1.7.5)

My survey is a simple json like this (please note number without double quotes):

```
{
  "delete": 2
}
```

The survey is filled correctly when requesting the resource via squest UI.

When I POST (via curl or python) the accept method indicating the survey, the number gets converted as a string

```
{
  "delete": "2"
}
```

This brings the process operation to fail with a 'NoneType' object has no attribute 'id' - not triggered if I correct the json survey by hand and remove double quotes.

The curl to post the accept method is like this :

`curl -X POST "https://[...]/api/service_catalog/request/233/accept/" -d '{ "delete": 2 }' -H 'Content-Type: application/json' -H "accept: application/json" -H "authorization: Bearer [...]"`

Same result when posting via python:

```
headers = { "Authorization": "Bearer [...]", 
            "Accept": "application/json",
            "Content-Type": "application/json" }

d = { 'delete': 2 }

endpoint = "https://[...]/api/service_catalog/request/233/accept/"
response = requests.post(endpoint, data=json.dumps(d), headers=headers)
```
As stated, after posting the accept method if I inspect the request's survey via API or UI the value has been converted to string.

I saw a [MR accepted in dev](https://github.com/HewlettPackard/squest/issues/528) a few days ago, but I didn't understand if that's related to this bug.

**Comment by Sispheor** [comment]
Done, fixed and merged in dev branch
