### ISSUE TITLE
Can't request delete operation from API

### ISSUE THREAD

**Issue by mr-falken** [HewlettPackard/squest#542]
When I try to request the delete operation fon an instance I got a stack trace from django (I'm on version 1.7.6b).

That's the curl I try to execute : 

`curl -X POST "https://[...]/api/service_catalog/instance/[...]/operation/[...]/request/" -d '{ "fill_in_survey": { }  }'  -H 'Content-Type: application/json' -H  "accept: application/json" -H  "authorization: Bearer [...]"`

And that's the django stack trace :

```
[...]
  File "/app/service_catalog/models/request.py", line 62, in full_survey
    return {k: v for k, v in {**self.fill_in_survey, **self.admin_fill_in_survey}.items() if v is not None}

Exception Type: TypeError at /api/service_catalog/instance/[...]/operation/[...]/request/
Exception Value: 'str' object is not a mapping
Request information:
USER: admin

GET: No GET data
POST: No POST data
FILES: No FILES data
COOKIES: No cookie data
[...]
```
Please note that deleting from UI works as expected.

**Comment by EliasBoulharts** [comment]
I tried to reproduce but it seems working for me to request a DELETE operation without survey. Do you have a survey?

**Comment by mr-falken** [comment]
Hi @EliasBoulharts ,
  yes, sorry I didn't mention that: I have a simple survey like this
  
  ```
{
    "delete": 2
}
```

I tried also to pass the survey in the post body, like :

`[...] -d '{ "fill_in_survey": {  "delete": 2 } }' [...]`

But got the same error.

As further information, after the djiango stack trace the resource goes in "DELETING" state but no awx task is triggered.

**Comment by mr-falken** [comment]
Sorry to bother again on this issue, but delete operation request via POST seems still broken on 1.8.0

I also tried calling a delete operation that doesn't need a survey, but still facing this error.

You mentioned that you didn't face that issue with an operation without survey, did you send "request_comment" (which seems mandatory in swagger) in your post ?

Can you share with me a simple curl that's working for you ?

Please note that I'm not deleting an instance, I am requesting a delete operation. :)

**Comment by EliasBoulharts** [comment]
I did a manual test and I can reproduce. Unfortunaly the 1.8.1 will be comming soon...

Thank you for your report.

**Comment by EliasBoulharts** [comment]
Fixed

**Comment by mr-falken** [comment]
Hi @EliasBoulharts,
  it works like a charm, thanks for helping! :)
