### ISSUE TITLE
Make mail_from a configurable setting

### ISSUE THREAD

**Issue by djvl** [HewlettPackard/squest#574]
I would like to be able to choose the from email address. We try to setup email notifications, but run into the following issue:

````
squest-celery-beat-1    | smtplib.SMTPSenderRefused: (530, b'5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM', 'squest@domain.tld')
````
This is because the organization only allow certain email address for mailer functionality. Only 'no-reply@domain.tld' is allowed in this case for the SMTP user.

I suspect it is fairly easy to implement by changing 'DEFAULT_FROM_EMAIL = f"squest@{settings.SQUEST_EMAIL_HOST}"' in 'service_catalog/mail_utils.py'.

Is this something that someone can look into, otherwise I will give it a shot myself (no real dev).

**Comment by Sispheor** [comment]
Yes indeed. I have no idea why we've hard coded something here.
I'll try to update it asap.
