### ISSUE TITLE
Question about Jinja2 in Surveys

### ISSUE THREAD

**Issue by janhoelscher** [HewlettPackard/squest#595]
Hey, 

i´m trying to use jinja2 templating inside the survey. 

Could someone please explain me, how to use this correctly? 

I have added {{ instance.name }} as the default variable. In this case for my requested hostname. 

But this jinja2 won´t be evaluated and hostname is empty in Review View as an Admin. 

Thanks for this awesome tool!

**Comment by Sispheor** [comment]
Sorry for the delay. It may be a bug. We are going to take a look.
It's a day 2 operation?
Because of course on creation the instance name is not there yet.

**Comment by Sispheor** [comment]
Just tested on my side it's ok.
![image](https://github.com/HewlettPackard/squest/assets/2573405/cf4dc1c7-fae0-4c65-82d7-895a9ac337a3)

![image](https://github.com/HewlettPackard/squest/assets/2573405/389b1d5d-779c-4369-8911-1b81de97c78f)
