### ISSUE TITLE
Refactoring Global Hook 

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#602]
Split RequestStateHook and InstanceStateHook creation to remove AJAX

## Abstract Class
One abstract class AbstractStateHook:
- [ ] Common fields
- [ ] Common method

## Models
Two model:
- [ ] RequestStateHook
  - [ ] Specific fields
    - [ ] state restricted to RequestState enumeration
  - [ ] Specific methods
- [ ] InstanceStateHook
  - [ ] Specific fields
    - [ ] state restricted to InstanceState enumeration
  - [ ] Specific methods

**Comment by Sispheor** [comment]
Done and merged in dev branch
