### ISSUE TITLE
Add user data to context

### ISSUE THREAD

**Issue by M-JANDAR12** [HewlettPackard/squest#636]
When ordering an instance it's not possible to add user data (username, email ,.etc..) as default fields. this could be done by adding the user to the context.

**Comment by EliasBoulharts** [comment]
What do you mean by "when ordering an instance"? User data are sent to the ansible controller (AAP or AWX), you ucan find the requester in squest.request.user or the instance spoc in squest.request.instance.spoc.

**Comment by Sispheor** [comment]
User is already in the context when ordering an instance. It's part of the data sent to Tower.

**Comment by Sispheor** [comment]
Oh sorry, I misunderstood. You mean in the "default" of the survey.
I'll add it

**Comment by Sispheor** [comment]
Done and merged in dev branch
