### ISSUE TITLE
text_attributes are required when creating a new resource in a resource group with API request

### ISSUE THREAD

**Issue by M-JANDAR12** [HewlettPackard/squest#658]
**Describe the bug**
In my use case, my resource group doesn't have any text_attributes just Computable attributes. but text_attributes field is required and i can't set it to null, so i have to create one in order to add resource with this POST api request "resource_tracker/resource_group/resource_group_id/resources/"

**To Reproduce**
1. Create a resource group without any text_attributes
2. try adding a new resource to this group with a api request

**Comment by Sispheor** [comment]
You can just set the flag but empty.

But I'm sorry to inform you that the v2 is coming and we have removed text attributes. As this kind of info can be placed in instance spec.

I close the issue as we are not going to change it.

**Comment by M-JANDAR12** [comment]
okey great, I don't see text_attributes being useful
thanks
