### ISSUE TITLE
Feature: Announcements

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#66]
Admin can create an announcement message with start and end date to notify users of an incoming maintenance

**Comment by Sispheor** [comment]
New model `Announcement` to be created:

- **date_created**: date when this message has been created in the DB
- **date_start**: date when the message start appearing on all users dashboard
- **date_stop**: date when the message stop appearing on all users dashboard
- **message**: the text message to show
- **type**: the type would map a color (success, primary, danger, warning...)
- **created_by**: user who created the Announcement message (foreign key User)

**Comment by Sispheor** [comment]
- [ ] Add Annoucements item in settings
- [ ] CRUD Annoucements
- [ ] Show annoucements in dashboards (Admin and Users)

**Comment by a-belhadj** [comment]
Done and merged in sub-dev
