### ISSUE TITLE
missing signature key

### ISSUE THREAD

**Issue by vishnugonela** [HewlettPackard/squest#692]
**Describe the bug**

**To Reproduce**
1. Go to 'git repo'
2. Click on 'run 'docker-compose up''
[+] Running 0/8
 ⠇ redis-cache Pulling                                                              5.9s
 ⠇ celery-beat Pulling                                                              5.9s
 ⠇ django Pulling                                                                   5.9s
 ⠇ celery-worker Pulling                                                            5.9s
 ⠇ db Pulling                                                                       5.9s
 ⠇ nginx Pulling                                                                    5.9s
 ⠇ maintenance Pulling                                                              5.9s
 ⠇ rabbitmq Pulling                                                                 5.9s
missing signature key

**Expected behavior**

**Screenshots**

**Additional context**

- Squest version or GIT commit number: 
- Ansible Tower/AWX version:

**Comment by Sispheor** [comment]
Hello,
We are not able to reproduce.
What is your Docker version? Seems that this kind of issue is related to too old docker version.

**Comment by vishnugonela** [comment]
Hi @Sispheor ,

Below is the docker version installed on Cenots7.9

[root@vm-37-40 squest]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64
 Experimental:    false
[root@vm-37-40 squest]#

**Comment by Sispheor** [comment]
So yes, this docker version is 7 years old. You should upgrade.

**Comment by vishnugonela** [comment]
Yes @Sispheor , it is working. Thank you. 

BTW, I am in HPE and deployed in our cluster sucessfully. 
http://10.188.37.40:8088/ui/

**Comment by Sispheor** [comment]
Nice! Don't hesitate to ping me on teams then !
Have fun with squest!

**Comment by vishnugonela** [comment]
Sure. Thank you.
