### ISSUE TITLE
RequestNotification/InstanceNotificationFilter filter not saved

### ISSUE THREAD

**Issue by a-belhadj** [HewlettPackard/squest#719]
**Describe the bug**
RequestNotification filter not saved properly for fields services and operations. 

Same for InstanceNotification for field services. It seems that it's a bug with m2m fields

**To Reproduce**
1. Create a RquestNotification filter
2. Add services and opreations
3. Save it
4. Edit it
5. Services and operations are not set

**Expected behavior**
Make it works

- Squest version or GIT commit number: v2.2.0 - d46ce7
- Ansible Tower/AWX version: N/A

**Comment by Sispheor** [comment]
Done and merged in dev branch
