### ISSUE TITLE
Squest > 2.1.1 error with trusted origins (due to the switch to Django 4)

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#725]
Workaround: configure "CSRF_TRUSTED_ORIGINS" in settings.

It's not yet wrapped by environment variables. 
Fix is coming soon.

**Comment by Sispheor** [comment]
done

**Comment by depasseg** [comment]
Is this supposed to be resolved?  Because I can't figure out how to incorporate another origin.

**Comment by a-belhadj** [comment]
Doc here: https://hewlettpackard.github.io/squest/2.5.1/configuration/squest_settings/#csrf_trusted_origins

**Comment by depasseg** [comment]
Ahh, TY.  Didn't know I needed to put the entire line in squest.env

I originally tried: CSRF_TRUSTED_ORIGINS=http://10.242.147.155:8080
Turns out I needed CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8080,http://localhost:8080,http://10.242.147.155:8080
