### ISSUE TITLE
User want to see who can accept/approve request

### ISSUE THREAD

**Issue by EliasBoulharts** [HewlettPackard/squest#733]
Add permission to display the list of approver:

- [ ] Create the permission view_who_can_accept_request on request
- [ ] Display the list in tab/popup/?

**Comment by a-belhadj** [comment]
New permission: list_approvers that allow users to see a list with all approvers.
Screenshot below

![image](https://github.com/HewlettPackard/squest/assets/82872898/44987a28-5706-4d8d-8c84-7a86a218803b)

**Comment by Sispheor** [comment]
Done and merged in dev branch
