### ISSUE TITLE
Error 500 when requesting a service

### ISSUE THREAD

**Issue by a-belhadj** [HewlettPackard/squest#774]
**Describe the bug**
Bug from user when trying to create a service request. 
Seems that data coming from the first form (Wizard here) were lost

**To Reproduce**
Unable to reproduce

**Screenshots**
![image](https://github.com/HewlettPackard/squest/assets/82872898/a650c4f5-5646-44bf-91aa-95e06c095ea6)

- Squest version or GIT commit number:   v2.5.1 - dc6c14 
- Ansible Tower/AWX version: N/A

**Comment by Sispheor** [comment]
Not able to reproduce since. I close this one.
