### ISSUE TITLE
Feature: Add theForeman as a backend

### ISSUE THREAD

**Issue by FlanniganColum** [HewlettPackard/squest#797]
**Description of the feature**
This is a very interesting tool from what i have been reading and im looking to over more self service, and was wondering if some connection to theForeman tool to run the ansible role against a specific server would be interesting. 

**Describe the solution you'd like**
Not sure if this is in scope, but basically a user being able to select MySQL/Docker, etc.. to deploy on there host through the ansible roles that way they dont need to wait for IT, it would just get submitted than approved by an IT member and it would auto deploy through theForeman API... 

Note: i have not installed this product, i am just reading up on it right now. As i dont use RedHat automation or AWS

**Comment by Sispheor** [comment]
Hi,

It's not in our scope to connect Squest to other backend than AWX/RHAAP.
That being said, if the "theForeman" has an api you can discuss with it via squest (by having an AWX in the middle anyway 😃).
